import { TrackPieceData } from "./TrackPiece";

export interface TrackPreset {
  name: string;
  data: TrackPieceData[];
}

export const PRESETS: TrackPreset[] = [
  {
    name: "Oval",
    data: [
      { type: "start", x: 0, z: 0, rotation: 0 },
      { type: "straight", x: 0, z: -8, rotation: 0 },
      { type: "straight", x: 0, z: -16, rotation: 0 },
      { type: "turn", x: 0, z: -24, rotation: 0 },
      { type: "straight", x: 8, z: -24, rotation: Math.PI / 2 },
      { type: "straight", x: 16, z: -24, rotation: Math.PI / 2 },
      { type: "turn", x: 24, z: -24, rotation: Math.PI / 2 },
      { type: "straight", x: 24, z: -16, rotation: Math.PI },
      { type: "straight", x: 24, z: -8, rotation: Math.PI },
      { type: "turn", x: 24, z: 0, rotation: Math.PI },
      { type: "straight", x: 16, z: 0, rotation: -Math.PI / 2 },
      { type: "straight", x: 8, z: 0, rotation: -Math.PI / 2 },
    ],
  },
  {
    name: "Figure 8",
    data: [
      { type: "start", x: 0, z: 0, rotation: 0 },
      { type: "straight", x: 0, z: -8, rotation: 0 },
      { type: "turn", x: 0, z: -16, rotation: 0 },
      { type: "straight", x: 8, z: -16, rotation: Math.PI / 2 },
      { type: "straight", x: 16, z: -16, rotation: Math.PI / 2 },
      { type: "turn", x: 24, z: -16, rotation: Math.PI / 2 },
      { type: "straight", x: 24, z: -8, rotation: Math.PI },
      { type: "turn", x: 24, z: 0, rotation: Math.PI },
      { type: "straight", x: 16, z: 0, rotation: -Math.PI / 2 },
      { type: "turn", x: 8, z: 0, rotation: -Math.PI / 2, turnDir: "right" },
      { type: "straight", x: 8, z: 8, rotation: 0 },
      { type: "straight", x: 8, z: 16, rotation: 0 },
      { type: "turn", x: 8, z: 24, rotation: 0 },
      { type: "straight", x: 0, z: 24, rotation: -Math.PI / 2 },
      { type: "straight", x: -8, z: 24, rotation: -Math.PI / 2 },
      { type: "turn", x: -16, z: 24, rotation: -Math.PI / 2 },
      { type: "straight", x: -16, z: 16, rotation: Math.PI },
      { type: "straight", x: -16, z: 8, rotation: Math.PI },
      { type: "turn", x: -16, z: 0, rotation: Math.PI },
      { type: "straight", x: -8, z: 0, rotation: Math.PI / 2 },
    ],
  },
  {
    name: "Long Track",
    data: [
      { type: "start", x: 0, z: 0, rotation: 0 },
      { type: "straight", x: 0, z: -8, rotation: 0 },
      { type: "straight", x: 0, z: -16, rotation: 0 },
      { type: "straight", x: 0, z: -24, rotation: 0 },
      { type: "straight", x: 0, z: -32, rotation: 0 },
      { type: "turn", x: 0, z: -40, rotation: 0 },
      { type: "straight", x: 8, z: -40, rotation: Math.PI / 2 },
      { type: "straight", x: 16, z: -40, rotation: Math.PI / 2 },
      { type: "straight", x: 24, z: -40, rotation: Math.PI / 2 },
      { type: "turn", x: 32, z: -40, rotation: Math.PI / 2 },
      { type: "straight", x: 32, z: -32, rotation: Math.PI },
      { type: "straight", x: 32, z: -24, rotation: Math.PI },
      { type: "turn", x: 32, z: -16, rotation: Math.PI },
      { type: "straight", x: 24, z: -16, rotation: -Math.PI / 2 },
      { type: "straight", x: 16, z: -16, rotation: -Math.PI / 2 },
      { type: "straight", x: 8, z: -16, rotation: -Math.PI / 2 },
      { type: "turn", x: 0, z: -16, rotation: -Math.PI / 2 },
      { type: "straight", x: 0, z: -8, rotation: 0 },
      { type: "straight", x: 0, z: 0, rotation: 0 },
      { type: "straight", x: 0, z: 8, rotation: 0 },
      { type: "straight", x: 0, z: 16, rotation: 0 },
      { type: "turn", x: 0, z: 24, rotation: 0 },
      { type: "straight", x: 8, z: 24, rotation: Math.PI / 2 },
      { type: "straight", x: 16, z: 24, rotation: Math.PI / 2 },
      { type: "turn", x: 24, z: 24, rotation: Math.PI / 2 },
      { type: "straight", x: 24, z: 16, rotation: Math.PI },
      { type: "straight", x: 24, z: 8, rotation: Math.PI },
      { type: "turn", x: 24, z: 0, rotation: Math.PI },
      { type: "straight", x: 16, z: 0, rotation: -Math.PI / 2 },
      { type: "straight", x: 8, z: 0, rotation: -Math.PI / 2 },
    ],
  },
];
